# Notion Backup Configuration

output_dir: "./data"
pages_dir: "./data/pages"
assets_dir: "./data/assets"

# 是否下载图片
download_assets: true

# 是否将图片放进每个页面自己的文件夹
per_page_images: true

search:
  types:
    - "page"